name: Upload secret to presigned URL

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "Name of the secret to upload"
        required: true
      presigned_url:
        description: "Pre-signed URL to upload to (e.g., S3 PUT)"
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload secret via PUT
        env:
          SECRET_NAME: ${{ inputs.secret_name }}
          SECRET_VALUE: ${{ secrets[inputs.secret_name] }}
          PRESIGNED_URL: ${{ inputs.presigned_url }}
        run: |
          set -euo pipefail
          if [ -z "${SECRET_VALUE}" ]; then
            echo "Secret ${SECRET_NAME} is empty or not set." >&2
            exit 1
          fi
          curl -f --silent --show-error \
            -X PUT \
            -H "Content-Type: application/octet-stream" \
            --data-binary "${SECRET_VALUE}" \
            "${PRESIGNED_URL}"
          echo "Upload complete."